export enum PAYMENT_GATEWAY {
    FLUTTERWAVE = 'FLUTTERWAVE',
    UNIONBANK = 'UNIONBANK',
    PAYSTACK = 'PAYSTACK',
}

export enum PAYMENT_METHOD {
    GATEWAY = 'GATEWAY',
}

export enum PAYMENT_STATUS {
    PENDING = 'PENDING',
    SUCCESSFUL = 'SUCCESSFUL',
    FAIL = 'FAIL',
}
